[project]
name = "noormsql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name="Victor Pierozan", email="victor@pierozan.com" },
]
dependencies = [
    
]
